---
- name: Print out variables
  hosts: localhost
  gather_facts: false
  vars:
    dns1: 8.8.8.8
    dns2: 8.8.4.4
  vars_files:
    - my_vars.yml
  tasks:
    - name: Debugging...
      ansible.builtin.debug:
        msg: "{{ ip_addr1 }}"

    - name: Var from inventory
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"
