---
- name: Deploy firewall management policy
  hosts: pod99-mgmt
  gather_facts: false
  vars:
    fw_policy_mgmt_rules:
      - name: "Ansible Management Access"
        source:
          - Ansible Server
          - Windows SmartConsole
          - Windows SmartConsole Public
        destination:
          - "{{ fw_name }}"
        service: Any
        action: "Accept"
        position: 1
      - name: "SSH Access"
        source: Any
        destination:
          - "{{ fw_name }}"
        service: SSH
        action: "Accept"
        position: 2

  tasks:
    - name: Firewall management rules
      check_point.mgmt.cp_mgmt_access_rule:
        layer: "Network"
        name: "{{ item.name }}"
        source: "{{ item.source }}"
        destination: "{{ item.destination }}"
        service: "{{ item.service }}"
        action: "{{ item.action }}"
        position: "{{ item.position }}"
      loop: "{{ fw_policy_mgmt_rules }}"
      notify:
        - FW Publish
        - Install Policy

  handlers:
    - name: FW Publish
      check_point.mgmt.cp_mgmt_publish:

    - name: Install Policy
      check_point.mgmt.cp_mgmt_install_policy:
        policy_package: "Standard"
        targets:
          - "{{ fw_name }}"
      # async: 900
      # poll: 10
