---
- name: Network object group
  hosts: mgmt
  gather_facts: false
  tasks:
    - name: Create 'hq_net' group
      check_point.mgmt.cp_mgmt_group:
        name: hq_net
        members:
          - hq_net_128
          - hq_net_129
          - hq_net_130
          - hq_net_131
          - hq_net_132
          - hq_net_133
          - hq_net_134
          - hq_net_135
        color: blue
        state: present
      notify: FW Publish

  handlers:
    - name: FW Publish
      check_point.mgmt.cp_mgmt_publish:
