---
- name: Exercise 2c
  hosts: gaia
  gather_facts: false
  tasks:
    - name: Print 'dns1' and 'eth1' IP address for gaia hosts
      ansible.builtin.debug:
        msg: |
          "Primary DNS for host {{ inventory_hostname }} is {{ dns1 }}"
          "The 'eth1' interface IP (fictional) is {{ eth1 }}"
