---
- name: Debug Collection Paths
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure /etc/ansible exists
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        mode: '0755'

    - name: Create the empty hosts file
      ansible.builtin.file:
        path: /etc/ansible/hosts
        state: touch
        mode: '0644'

    - name: Try to find the Gaia collection on disk
      ansible.builtin.shell: "ansible-galaxy collection list"
      register: collection_list

    - name: Show installed collections
      ansible.builtin.debug:
        var: collection_list.stdout_lines

- name: Gaia checks
  hosts: gaia
  gather_facts: no
  # vars:
  #   ansible_network_os: check_point.gaia.checkpoint
  tasks:
    - name: Gaia tests
      ansible.builtin.debug:
        msg: |
          {{ ansible_host }}

#    - name: Show Version
#      check_point.gaia.cp_gaia_version_facts:
#      register: result
#
#    - ansible.builtin.debug:
#        var: result
