---
- name: Debug Collection Paths
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Try to find the Gaia collection on disk
      ansible.builtin.shell: "ansible-galaxy collection list"
      register: collection_list

    - name: Show installed collections
      ansible.builtin.debug:
        var: collection_list.stdout_lines

- name: Gaia checks
  hosts: gaia
  gather_facts: no
  tasks:
    - name: Gaia tests
      ansible.builtin.debug:
        msg: |
          {{ ansible_host }}

    - name: Show Version
      check_point.gaia.cp_gaia_version_facts:
        version: null
        virtual_system_id: null
      register: result

    - ansible.builtin.debug:
        var: result
