---
- name: Config DNS servers
  hosts: pod99-gaia
  gather_facts: false

  vars:
    dns1: "172.31.0.2"
    dns2: "8.8.8.8"
    dns3: "8.8.4.4"
    dns_domain: lasthop.io
    # dns_domain: checkpoint.com

  tasks:
    - name: Config DNS servers
      check_point.gaia.cp_gaia_dns:
        suffix: "{{ dns_domain }}"
        primary: "{{ dns1 }}"
        secondary: "{{ dns2 }}"
        tertiary: "{{ dns3 }}"

    - name: "Configure domainname (not idempotent)"
      check_point.gaia.cp_gaia_run_script:
        script: clish -c "set domainname {{ dns_domain }}"
      notify: Gaia Save Config

  handlers:
    - name: Gaia Save Config
      check_point.gaia.cp_gaia_run_script:
        script: clish -c "save config"
